import React from "react";
import Stepper from "./Stepper"

class StepperExample extends React.Component {

state = {
  formActivePanel1: 1,
  formActivePanel1Changed: false,
}

swapFormActive = (a) => (param) => (e) => {
  this.setState({
    ['formActivePanel' + a]: param,
    ['formActivePanel' + a + 'Changed']: true
  });
}

handleNextPrevClick = (a) => (param) => (e) => {
  this.setState({
    ['formActivePanel' + a]: param,
    ['formActivePanel' + a + 'Changed']: true
  });
}

handleSubmission = () => {
  alert('Form submitted!');
}

calculateAutofocus = (a) => {
  if (this.state['formActivePanel' + a + 'Changed']) {
    return true
  }
}

render() {
  return (
      <section id="registration">
          <h2 class="section-heading">Registration form with steps</h2>

          <p class="description">The step indicator is generated by the component, basing on the <code>name</code> and <code>icon</code>props passed in with individual steps. </p>

          <section>
              <div class="row">
                  <div class="col-md-12">

                      <h2 class="text-center font-weight-bold pt-4 pb-5 mb-5"><strong>Registration form</strong></h2>

                      
                      <Stepper />
                      

                      <form role="form" action="" method="post">
                        <div class="row setup-content-2" id="step-1">
                          <div class="col-md-12">
                            <h3 class="font-weight-bold pl-0 my-4"><strong>Basic Information</strong></h3>
                            <div class="form-group md-form">
                              <label for="yourEmail-2" data-error="wrong" data-success="right">Email</label>
                              <input id="yourEmail-2" type="email" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form">
                              <label for="yourUsername-2" data-error="wrong" data-success="right">Username</label>
                              <input id="yourUsername-2" type="text" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form mt-3">
                              <label for="yourPassword-2" data-error="wrong" data-success="right">Password</label>
                              <input id="yourPassword-2" type="password" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form mt-3">
                              <label for="repeatPassword-2" data-error="wrong" data-success="right">Repeat Password</label>
                              <input id="repeatPassword-2" type="password" required="required" class="form-control validate"/>
                            </div>
                            <button class="btn btn-mdb-color btn-rounded nextBtn-2 float-right" type="button">Next</button>
                          </div>
                        </div>
                        <div class="row setup-content-2" id="step-2">
                          <div class="col-md-12">
                            <h3 class="font-weight-bold pl-0 my-4"><strong>Personal Data</strong></h3>
                            <div class="form-group md-form">
                              <label for="yourName-2" data-error="wrong" data-success="right">First Name</label>
                              <input id="yourName-2" type="text" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form mt-3">
                              <label for="secondName-2" data-error="wrong" data-success="right">Second Name</label>
                              <input id="secondName-2" type="text" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form">
                              <label for="surname-2" data-error="wrong" data-success="right">Surname</label>
                              <input id="surname-2" type="text" required="required" class="form-control validate"/>
                            </div>
                            <div class="form-group md-form mt-3">
                              <label for="yourAddress-2" data-error="wrong" data-success="right">Address</label>
                              <textarea id="yourAddress-2" type="text" required="required" rows="2" class="md-textarea validate form-control"></textarea>
                            </div>
                            <button class="btn btn-mdb-color btn-rounded prevBtn-2 float-left" type="button">Previous</button>
                            <button class="btn btn-mdb-color btn-rounded nextBtn-2 float-right" type="button">Next</button>
                          </div>
                        </div>
                        <div class="row setup-content-2" id="step-3">
                          <div class="col-md-12">
                            <h3 class="font-weight-bold pl-0 my-4"><strong>Terms and conditions</strong></h3>
                            <div class="form-group">
                              <input type="checkbox" id="checkbox111" class="form-check-input"/>
                              <label for="checkbox111" class="form-check-label">I agree to the terms and conditions</label>
                            </div>
                            <div class="form-check">
                              <input type="checkbox" id="checkbox112" class="form-check-input" />
                              <label for="checkbox112" class="form-check-label">I want to receive newsletter</label>
                            </div>
                            <button class="btn btn-mdb-color btn-rounded prevBtn-2 float-left" type="button">Previous</button>
                            <button class="btn btn-mdb-color btn-rounded nextBtn-2 float-right" type="button">Next</button>
                          </div>
                        </div>
                        <div class="row setup-content-2" id="step-4">
                          <div class="col-md-12">
                            <h3 class="font-weight-bold pl-0 my-4"><strong>Finish</strong></h3>
                            <h2 class="text-center font-weight-bold my-4">Registration completed!</h2>
                            <button class="btn btn-mdb-color btn-rounded prevBtn-2 float-left" type="button">Previous</button>
                            <button class="btn btn-success btn-rounded float-right" type="submit">Submit</button>
                          </div>
                        </div>
                      </form>

      </div>

    </div>

  </section>



</section>
    );
  };
}

export default StepperExample;